WebApplication1/Models/Director.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Director
    {
        public string name;
        public string lname;
        public string phone;
        public Director(string name, string lname, string phone)
        {
            this.name = name;
            this.lname = lname;
            this.phone = phone;
        }
    }
}

WebApplication1/Models/Pupil.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Pupil
    {
        public string name;
        public string lname;
        public int yearBorn;
        public int great;
     public  Pupil(string name,string lname,int yearBorn,int great)
        {
            this.name = name;
            this.lname = lname;
            this.yearBorn = yearBorn;
            this.great = great;
        }
    }
}

WebApplication1/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Teacher
    {
        public string name;
        public string lname;
        public int year;
        public int monney;
        public Teacher(string name, string lname, int year, int monney)
        {
            this.name = name;
            this.lname = lname;
            this.year = year;
            this.monney = monney;
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Controllers/PupilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PupilController : Controller
    {
        // GET: Pupil
        public ActionResult Index()
        {
            ViewBag.Name = "keren";
            return View();
        }
        public ActionResult ShowPupil()
        {
            ViewBag.NamePupil = "keren";
            return View();
        }
        public ActionResult ShowNamesPupils()
        {
            ViewBag.arrayNames=new string[] { "lior","dan","yaron","shlomi","shilat","avi"};
            return View();
        }
        public ActionResult ShowAllPupils()
        {
            ViewBag.arrayNames = new string[] { "lior", "dan", "yaron", "shlomi", "shilat", "avi" };
            return View();
        }

        public ActionResult ReturnArrayInJson()
        {
            string[] arrayToJson= new string[] { "lior", "dan", "yaron", "shlomi", "shilat", "avi" };
            return Json(arrayToJson, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ClassPupil()
        {
            Pupil pupil1 = new Pupil("keren", "hailu", 1998, 5);
            ViewBag.classPupil=pupil1;
            return View();
        }
        public ActionResult ClassPupilWithModel()
        {
            //Pupil pupil2 = newObj();
            //return View(pupil2);
            return View(newObj());
        }

        private static Pupil newObj()
        {
            return new Pupil("tikva", "yosef", 1996, 6);
        }

        public ActionResult ListPupil()
        {
            //List<Pupil> pupils = NewMethod();
            //return View(pupils);
            return View(NewMethod());

        }

        private static List<Pupil> NewMethod()
        {
            Pupil pupilOne = new Pupil("tikva", "yosef", 1996, 6);
            Pupil pupilTwo = new Pupil("keren", "hailu", 1998, 8);
            Pupil pupilThree = new Pupil("eden", "genet", 1997, 7);
            Pupil pupilFour = new Pupil("yafit", "smuel", 1999, 5);
            List<Pupil> pupils = new List<Pupil>();
            pupils.Add(pupilOne);
            pupils.Add(pupilTwo);
            pupils.Add(pupilThree);
            pupils.Add(pupilFour);
            return pupils;
        }
    }
}

WebApplication1/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ShowTeacher()
        {
            ViewBag.TeacherName = "yakov";
            return View();
        }
        public ActionResult ShowAllTeachers()
        {
            ViewBag.AllTeachersName = new string[] { "shlomo", "aschalow", "yakov", "morit", "asaf", "takla" };
            return View();
        }
        public ActionResult TenRandomNumbers()
        {
            ViewBag.arrayNames = new int[10];

            Random random = new Random();
            for (int i = 0; i < 10; i++)
            {
                ViewBag.arrayNames[i] = random.Next(1, 10);
            }
            return View();
        }

        public ActionResult ShowNameLongerThan4()
        {
            ViewBag.famaliyNames = new string[] { "hailu", "levi", "choen", "shalom", "asaf", "takla","yosef","eyal","lolo","shoko" };
            return View();
        }
        public ActionResult ClassTeacher()
        {
            Teacher teacher1 = new Teacher("yosef", "choen", 1970, 40);
            ViewBag.TeacherClass = teacher1;
            return View();
        }
        public ActionResult ClassTeacherWithModel()
        {
            Teacher teacher2 = new Teacher("yosef", "lior", 1980, 42);
            return View(teacher2);

        }
        public ActionResult ClassDirector()
        {
            Director director1 = new Director("dan", "levi", "0543812");
            ViewBag.DirectorClass = director1;
            return View();
        }
        public ActionResult ClassDirectorWithModel()
        {
            Director director2 = new Director("avi", "shalom", "0542222");
            return View(director2);
            
        }
        //public ActionResult buttonToTeacher()
        //{
            
        //    return View();
        //}
    }

}

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication1/Views/Pupil/ClassPupil.cshtml
@{
    ViewBag.Title = "ClassPupil";
}

<h2>ClassPupil</h2>
<h1>name : @ViewBag.classPupil.name</h1>
<h1>lname : @ViewBag.classPupil.lname</h1>
<h1>year born : @ViewBag.classPupil.yearBorn</h1>
<h1>great : @ViewBag.classPupil.great</h1>

WebApplication1/Views/Pupil/ClassPupilWithModel.cshtml
@{
    ViewBag.Title = "ClassPupilWithModel";
}

<h2>ClassPupilWithModel</h2>
<h4>@Model.name</h4>
<h4>@Model.lname</h4>
<h4>@Model.yearBorn</h4>
<h4>@Model.great</h4>

WebApplication1/Views/Pupil/Index.cshtml
@*@{
    ViewBag.Title = "Index";
}*@

<h2>name os pupil</h2>
<h3>@ViewBag.Name</h3>

WebApplication1/Views/Pupil/ListPupil.cshtml
@{
    ViewBag.Title = "ListPupil";
}

<h2>ListPupil</h2>
@*שתי תשובות*@ 
@for (var i = 0; i < Model.Count; i++)
{
    <h4>name : @Model[i].name</h4>
    <h4>lname : @Model[i].lname</h4>
    <h4>yearBorn : @Model[i].yearBorn</h4>
    <h4>great : @Model[i].great</h4>
    @*<h4>-----------------------------</h4>*@
    <hr />

}


@*@foreach (var item in Model)
{
    <h4>name : @item.name</h4>
    <h4>lname : @item.lname</h4>
    <h4>yearBorn : @item.yearBorn</h4>
    <h4>great : @item.great</h4>
}*@

WebApplication1/Views/Pupil/ShowNamesPupils.cshtml
@*@{
    ViewBag.Title = "ShowNamesPupils";
}*@

@foreach(string item in ViewBag.arrayNames)
            {
                <h3>@item</h3>
            }
<h3>@ViewBag.arrayNames</h3>

WebApplication1/Views/Pupil/ShowPupil.cshtml
@{
    ViewBag.Title = "ShowPupil";
}

<h2>ShowPupil</h2>
<h3>@ViewBag.NamePupil</h3>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
        <li>@Html.ActionLink("ShowPupil", "ShowPupil", "Pupil")</li>*@
                    @*<li>@Html.ActionLink("ShowNamesPupils", "ShowNamesPupils", "Pupil")</li>
                    <li>@Html.ActionLink("ShowAllTeachers", "ShowAllTeachers", "Teacher")</li>
                    <li>@Html.ActionLink("ShowTeacher", "ShowTeacher", "Teacher")</li>
                    <li>@Html.ActionLink("TenRandomNumbers", "TenRandomNumbers", "Teacher")</li>
                    <li>@Html.ActionLink("ClassPupil", "ClassPupil", "Pupil")</li>*@
                    <li>@Html.ActionLink("ClassPupilWithModel", "ClassPupilWithModel", "Pupil")</li>
                    <li>@Html.ActionLink("ClassTeacherWithModel", "ClassTeacherWithModel", "Teacher")</li>
                    <li>@Html.ActionLink("ClassTeacher", "ClassTeacher", "Teacher")</li>
                    <li>@Html.ActionLink("ClassDirector", "ClassDirector", "Teacher")</li>
                    <li>@Html.ActionLink("ClassPupil", "ClassPupil", "Pupil")</li>
                    <li>@Html.ActionLink("ListPupil", "ListPupil", "Pupil")</li>









                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Teacher/ClassDirector.cshtml
@{
    ViewBag.Title = "ClassDirector";
}

<h2>ClassDirector</h2>
<h4>@ViewBag.DirectorClass.name</h4>
<h4>@ViewBag.DirectorClass.lname</h4>
<h4>@ViewBag.DirectorClass.phone</h4>

WebApplication1/Views/Teacher/ClassDirectorWithModel.cshtml
@{
    ViewBag.Title = "ClassDirectorWithModel";
}

<h2>ClassDirectorWithModel</h2>
<h4>@Model.name</h4>
<h4>@Model.lname</h4>
<h4>@Model.phone</h4>

WebApplication1/Views/Teacher/ClassTeacher.cshtml
@{
    ViewBag.Title = "ClassTeacher";
}

<h2>ClassTeacher</h2>
<h1>name : @ViewBag.TeacherClass.name</h1>
<h1>lname : @ViewBag.TeacherClass.lname</h1>
<h1>year : @ViewBag.TeacherClass.year</h1>
<h1>monney : @ViewBag.TeacherClass.monney $</h1>

@Html.ActionLink("link to page","index","Pupil")

WebApplication1/Views/Teacher/ClassTeacherWithModel.cshtml
@{
    ViewBag.Title = "ClassTeacherWithModel";
}

<h2>ClassTeacherWithModel</h2>
<h4>@Model.name</h4>
<h4>@Model.name</h4>
<h4>@Model.year</h4>
<h4>@Model.monney</h4>

WebApplication1/Views/Teacher/ShowAllTeachers.cshtml
@{
    ViewBag.Title = "ShowAllTeachers";
}

<h2>ShowAllTeachers</h2>
@foreach(string item in ViewBag.AllTeachersName)
            {
                <h3>@item</h3>
            }
 

WebApplication1/Views/Teacher/ShowNameLongerThan4.cshtml
@{
    ViewBag.Title = "ShowNameLongerThan4";
}

<h2>ShowNameLongerThan4</h2>
@for (var i = 0; i < 10; i++)
{
    if (ViewBag.famaliyNames[i].Length > 4)
    {
        <h1>@ViewBag.famaliyNames[i]</h1>
    }
}

WebApplication1/Views/Teacher/ShowTeacher.cshtml
@{
    ViewBag.Title = "ShowTeacher";
}

<h2>ShowTeacher :</h2>
<h3>@ViewBag.TeacherName</h3>

WebApplication1/Views/Teacher/TenRandomNumbers.cshtml
@*@{
    ViewBag.Title = "TenRandomNumbers";
}*@

<h2>TenRandomNumbers</h2>
@*<h3>@ViewBag.arrayNames</h3>*@
@for (int i = 0; i < 10; i++)
{
    if (ViewBag.arrayNames[i] % 2 == 0)
    {
        <h1>@ViewBag.arrayNames[i]</h1>;
    }
}